---
title: "Cliff Muriu"
subtitle: "Data Analyst| Business Insights"
about:
  template: trestles
  links:
    - icon: github
      text: GitHub
      href: https://github.com/cliffmuriu
    - icon: envelope
      text: Email
      href: mailto:cliffmuriu01@gmmail.com
    - icon: whatsapp
      text: WhatsApp
      href: https://wa.me/254742950424
---

## Hello, I'm Cliff Muriu

I am a data enthusiast based in Kenya, passionate about turning raw data into clear business decisions. I build dashboards, analyze trends and tell stories with data using **R, and Excel.**

> "Data is not just numbers — it's answers waiting to be discovered."

### What I Do

**📊 Data Analysis & Visualization** I clean, analyze, and visualize datasets to uncover patterns using R (Tidyverse, ggplot2) .

**📈 Business Intelligence** Building interactive dashboards and reports that help businesses track performance and make data-driven decisions.

**🤖 Learning & Growing** Currently expanding into Machine Learning and Predictive Analytics for real-world problem solving.

### Featured Projects

+----------------------------------+-------------------+----------------------------------+
| Project                          | Tools             | Link                             |
+==================================+===================+==================================+
| **Analysis of maize production** | R, ggplot2, dplyr | [View Project](cat1-project.qmd) |
|                                  |                   |                                  |
| **in kenya across 47 counties**  |                   |                                  |
+----------------------------------+-------------------+----------------------------------+

### Tech Stack

`R` `Python` `Excel` `Quarto` `Git & GitHub` `ggplot2` `Tidyverse` `Power BI`

### Let's Connect

I am open to internships, freelance data projects, and collaborations.

**Have data that needs a story? Let's talk.**

[Download My CV](files/CV_Cliff_Muriu.pdf) \| [Email Me](mailto:cliffmuriu01@email.com)

------------------------------------------------------------------------

*This site was built with Quarto and hosted on GitHub Pages. Last updated: 07/10/2026*
